[Distribution]
Distribution=custom
Architecture=arm64

[Output]
Format=directory
Output=bk-nabu-rootfs
OutputDirectory=../output

[Content]
BaseTrees=../cache/ArchLinuxARM-aarch64-latest.tar.gz
CleanPackageMetadata=no
Bootable=no

[Build]
BuildSources=
WorkspaceDirectory=../build/mkosi-workspace
CacheDirectory=../cache/mkosi
PackageCacheDirectory=../cache/pacman
